export const supported_diseases = [
	"Apple alternaria leaf spot",
	"Apple black rot",
	"Apple brown spot",
	"Apple gray spot",
	"Apple rust",
	"Apple scab",
	"Bell pepper bacterial spot",
	"Cassava bacterial blight",
	"Cassava brown streak disease",
	"Cassava green mottle",
	"Cassava mosaic disease",
	"Cherry powdery mildew",
	"Corn common rust",
	"Corn gray leaf spot",
	"Corn northern leaf blight",
	"Grape black measles",
	"Grape black rot",
	"Grape isariopsis leaf spot",
	"Grape leaf blight",
	"Orange citrus greening",
	"Peach bacterial spot",
	"Potato bacterial wilt",
	"Potato early blight",
	"Potato late blight",
	"Potato nematode",
	"Potato pests",
	"Potato phytophthora",
	"Potato virus",
	"Rice bacterial blight",
	"Rice blast",
	"Rice brown spot",
	"Rice tungro",
	"Squash powdery mildew",
	"Sugarcane mosaic",
	"Sugarcane red rot",
	"Sugarcane rust",
	"Sugarcane yellow leaf",
	"Tomato bacterial spot",
	"Tomato early blight",
	"Tomato late blight",
	"Tomato leaf curl",
	"Tomato leaf mold",
	"Tomato mosaic virus",
	"Tomato septoria leaf spot",
	"Tomato spider mites",
	"Tomato target spot",
];
